- block:
  - name: Remove user petya
    user:
      name: petya
      state: absent

  - name: Create the 'www' group
    group:
      name: www
      state: present

  - name: Create user 'www'
    user:
      name: www
      groups: www
      append: yes
  tags: [setup, users]

- block:
  - name: Set timezone to UTC+3
    timezone:
      name: Europe/Moscow
  tags: [setup, timezone]

- block:
  - name: Install unzip
    apt:
      name: unzip
      state: present
  tags: [setup, packages]
